sudo: false
language: python
python: 3.4
install:
  - pip install coveralls
  - curl -L https://github.com/django/django/archive/master.tar.gz | tar zx
script: PYTHONPATH=django-master coverage run --source=django ./django-master/tests/runtests.py --failfast
after_success: coveralls
