language: python
install:
    - wget https://github.com/django/django/archive/master.tar.gz
    - tar zxf master.tar.gz
script:
    - cd django-master/tests && PYTHONPATH=.. python3 ./runtests.py --failfast
